# default_language_version:
#   python: python3.9

repos:

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args: [
        --in-place,
        --ignore-init-module-imports,
        --remove-unused-variables,
        --remove-all-unused-imports,
      ]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      # language_version: python3.9

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    - id: mypy

  - repo: local
    hooks:
    - id: pycodestyle
      name: pycodestyle
      entry: pycodestyle
      language: system
      args: [
        '--ignore=E722,E126',
        '--max-line-length=79',
        '--exclude=*init*'
      ]
      files: \.py$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-docstring-first
    - id: check-added-large-files
    - id: check-yaml
      args: [--allow-multiple-documents]
