# syntax=docker/dockerfile:1

FROM python:3.9-alpine3.16

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add --update --no-cache curl gcc musl-dev

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

ENTRYPOINT ["sh", "docker_entrypoint.sh"]
