---
network.host: "0.0.0.0"
http.host: 0.0.0.0

# Security
xpack.security.enabled: true

# HTTP security setttings
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: certs/es-master/es-master.key
xpack.security.http.ssl.certificate: certs/es-master/es-master.crt
xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt

# Transport security settings
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: certs/es-master/es-master.key
xpack.security.transport.ssl.certificate: certs/es-master/es-master.crt
xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
xpack.security.transport.ssl.verification_mode: certificate
